//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.ReturnMessages", typeof(ReturnMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to activate the selected coupon(s), please refresh the page and try again.
        /// </summary>
        public static string ActivateCouponError {
            get {
                return ResourceManager.GetString("ActivateCouponError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected coupon(s) were activated successfully.
        /// </summary>
        public static string ActivateCouponSuccess {
            get {
                return ResourceManager.GetString("ActivateCouponSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error changing your password, please make sure your old password is correct and that your new passwords match.
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error attempting to create this coupon, please refresh the page and try again.
        /// </summary>
        public static string CreateCouponError {
            get {
                return ResourceManager.GetString("CreateCouponError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupon was created successfully.
        /// </summary>
        public static string CreateCouponSuccess {
            get {
                return ResourceManager.GetString("CreateCouponSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to deactivate the selected coupon(s), please refresh the page and try again.
        /// </summary>
        public static string DeactivateCouponError {
            get {
                return ResourceManager.GetString("DeactivateCouponError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected coupon(s) were deactivated successfully.
        /// </summary>
        public static string DeactivateCouponSuccess {
            get {
                return ResourceManager.GetString("DeactivateCouponSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to delete the selected coupon, please refresh the page and try again.
        /// </summary>
        public static string DeleteCouponError {
            get {
                return ResourceManager.GetString("DeleteCouponError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected coupon was deleted successfully.
        /// </summary>
        public static string DeleteCouponSuccess {
            get {
                return ResourceManager.GetString("DeleteCouponSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating your business info, please refresh the page and try again.
        /// </summary>
        public static string UpdateBusinessInfoError {
            get {
                return ResourceManager.GetString("UpdateBusinessInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your business information has been updated successfully.
        /// </summary>
        public static string UpdateBusinessInfoSuccess {
            get {
                return ResourceManager.GetString("UpdateBusinessInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error uploading your menu, please refresh the page and try again.
        /// </summary>
        public static string UploadMenuError {
            get {
                return ResourceManager.GetString("UploadMenuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your menu has been uploaded successfully.
        /// </summary>
        public static string UploadMenuSuccess {
            get {
                return ResourceManager.GetString("UploadMenuSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error verifying your physical address, please verify the code you entered is correct.
        /// </summary>
        public static string VerifyPhysicalAddressError {
            get {
                return ResourceManager.GetString("VerifyPhysicalAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your physical address has been verified successfully.
        /// </summary>
        public static string VerifyPhysicalAddressSuccess {
            get {
                return ResourceManager.GetString("VerifyPhysicalAddressSuccess", resourceCulture);
            }
        }
    }
}
